#**************************************************************************
#*                                                                        *
#*                                 OCaml                                  *
#*                                                                        *
#*              Anil Madhavapeddy, OCaml Labs                             *
#*                                                                        *
#*   Copyright 2014 Institut National de Recherche en Informatique et     *
#*     en Automatique.                                                    *
#*                                                                        *
#*   All rights reserved.  This file is distributed under the terms of    *
#*   the GNU Lesser General Public License version 2.1, with the          *
#*   special exception on linking described in the file LICENSE.          *
#*                                                                        *
#**************************************************************************

sudo: false
language: c
git:
  submodules: false
script:
  - >
    mkdir ~/inst && ./configure --prefix ~/inst --with-debug-runtime &&
    make -j4 world.opt &&
    OCAMLRUNPARAM=v=0,V=1 make -C testsuite all-enabled

# For speed, only run a few compiler/OS combinations
matrix:
  include:
  - compiler: gcc
    os: linux
    env:
    - USE_RUNTIME: d
  - compiler: clang
    os: osx
