on: pull_request

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v4
        with:
          script: |
            const script = require('./tools/ci/actions/diff.js')
            await script({github, context})
