name: main

on: [push, pull_request]

jobs:

  build:
    name: 'linux'
    runs-on: 'ubuntu-latest'
    steps:
      - name: configure tree
        run: |
          MAKE_ARG=-j XARCH=x64 bash -xe tools/ci/actions/runner.sh configure
      - name: Build
        run: |
          MAKE_ARG=-j bash -xe tools/ci/actions/runner.sh build
      - uses: actions/upload-artifact@v2
        with:
          name: compiler
          path: .

  build-misc:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: linux-debug
            os: ubuntu-latest
            env: OCAMLRUNPARAM=v=0,V=1 USE_RUNTIME=d
          - name: macos
            os: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: configure tree
        run: |
          MAKE_ARG=-j XARCH=x64 bash -xe tools/ci/actions/runner.sh configure
      - name: Build
        run: |
          MAKE_ARG=-j bash -xe tools/ci/actions/runner.sh build
      - name: Run the testsuite
        run: |
          bash -xe tools/ci/actions/runner.sh test

  testsuite:
    needs: build
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idneeds    strategy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        total:
          - 4
        id:
          - debug
          - taskset
          - normal
          - super
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: compiler
      - name: Run the testsuite
        if: ${{ matrix.id == 'normal' }}
        run: |
          bash -xe tools/ci/actions/runner.sh test
      - name: Run the testsuite (Super Charged)
        if: ${{ matrix.id == 'super' }}
        run: |
          bash -xe tools/ci/actions/runner.sh testmore
      - name: Run the testsuite (s=4096, debug runtime)
        env:
          OCAMLRUNPARAM: s=4096,v=0
          USE_RUNTIME: d
        if: ${{ matrix.id == 'debug' }}
        run: |
          bash -xe tools/ci/actions/runner.sh test
      - name: Run the testsuite (taskset -c 0)
        if: ${{ matrix.name == 'taskset' }}
        run: |
          taskset -c 0 bash -xe tools/ci/actions/runner.sh test
